// Code generated by the Encore 1.49.1 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly booking: booking.ServiceClient
    public readonly event: event.ServiceClient
    public readonly group: group.ServiceClient
    public readonly realtime: realtime.ServiceClient
    public readonly recommendation: recommendation.ServiceClient
    public readonly sponsor: sponsor.ServiceClient
    public readonly user: user.ServiceClient
    public readonly venue: venue.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.booking = new booking.ServiceClient(base)
        this.event = new event.ServiceClient(base)
        this.group = new group.ServiceClient(base)
        this.realtime = new realtime.ServiceClient(base)
        this.recommendation = new recommendation.ServiceClient(base)
        this.sponsor = new sponsor.ServiceClient(base)
        this.user = new user.ServiceClient(base)
        this.venue = new venue.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { book as api_booking_book_book } from "~backend/booking/book";
import { checkIn as api_booking_checkin_checkIn } from "~backend/booking/checkin";
import { get as api_booking_get_get } from "~backend/booking/get";

export namespace booking {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.book = this.book.bind(this)
            this.checkIn = this.checkIn.bind(this)
            this.get = this.get.bind(this)
        }

        /**
         * Book tickets for an event
         */
        public async book(params: RequestType<typeof api_booking_book_book>): Promise<ResponseType<typeof api_booking_book_book>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bookings`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_booking_book_book>
        }

        /**
         * Check in a booking
         */
        public async checkIn(params: RequestType<typeof api_booking_checkin_checkIn>): Promise<ResponseType<typeof api_booking_checkin_checkIn>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bookings/checkin`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_booking_checkin_checkIn>
        }

        /**
         * Get booking details
         */
        public async get(params: { code: string }): Promise<ResponseType<typeof api_booking_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bookings/${encodeURIComponent(params.code)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_booking_get_get>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { get as api_event_get_get } from "~backend/event/get";
import { list as api_event_list_list } from "~backend/event/list";
import { search as api_event_search_search } from "~backend/event/search";

export namespace event {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.search = this.search.bind(this)
        }

        /**
         * Get single event with ticket details
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_event_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_event_get_get>
        }

        /**
         * Get events with availability
         */
        public async list(): Promise<ResponseType<typeof api_event_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_event_list_list>
        }

        /**
         * Search events with comprehensive filtering
         */
        public async search(params: RequestType<typeof api_event_search_search>): Promise<ResponseType<typeof api_event_search_search>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                availableOnly: params.availableOnly === undefined ? undefined : String(params.availableOnly),
                endDate:       params.endDate,
                eventType:     params.eventType,
                limit:         params.limit === undefined ? undefined : String(params.limit),
                maxPrice:      params.maxPrice === undefined ? undefined : String(params.maxPrice),
                minPrice:      params.minPrice === undefined ? undefined : String(params.minPrice),
                offset:        params.offset === undefined ? undefined : String(params.offset),
                query:         params.query,
                sortBy:        params.sortBy,
                sortOrder:     params.sortOrder,
                startDate:     params.startDate,
                venue:         params.venue,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_event_search_search>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    joinGroupBooking as api_group_book_joinGroupBooking,
    updateGroupSize as api_group_book_updateGroupSize
} from "~backend/group/book";
import {
    getChatMessages as api_group_chat_getChatMessages,
    sendMessage as api_group_chat_sendMessage
} from "~backend/group/chat";
import { create as api_group_create_create } from "~backend/group/create";
import {
    get as api_group_get_get,
    getUserGroupBookings as api_group_get_getUserGroupBookings
} from "~backend/group/get";
import {
    respondToInvitation as api_group_invite_respondToInvitation,
    sendInvitations as api_group_invite_sendInvitations,
    sendReminders as api_group_invite_sendReminders
} from "~backend/group/invite";
import {
    assignSeating as api_group_manage_assignSeating,
    getGroupCheckIn as api_group_manage_getGroupCheckIn,
    lockGroupBooking as api_group_manage_lockGroupBooking
} from "~backend/group/manage";

export namespace group {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.assignSeating = this.assignSeating.bind(this)
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.getChatMessages = this.getChatMessages.bind(this)
            this.getGroupCheckIn = this.getGroupCheckIn.bind(this)
            this.getUserGroupBookings = this.getUserGroupBookings.bind(this)
            this.joinGroupBooking = this.joinGroupBooking.bind(this)
            this.lockGroupBooking = this.lockGroupBooking.bind(this)
            this.respondToInvitation = this.respondToInvitation.bind(this)
            this.sendInvitations = this.sendInvitations.bind(this)
            this.sendMessage = this.sendMessage.bind(this)
            this.sendReminders = this.sendReminders.bind(this)
            this.updateGroupSize = this.updateGroupSize.bind(this)
        }

        /**
         * Assign seating for group members
         */
        public async assignSeating(params: RequestType<typeof api_group_manage_assignSeating>): Promise<ResponseType<typeof api_group_manage_assignSeating>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/seating`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_manage_assignSeating>
        }

        /**
         * Create a new group booking
         */
        public async create(params: RequestType<typeof api_group_create_create>): Promise<ResponseType<typeof api_group_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_create_create>
        }

        /**
         * Get group booking details by invite code
         */
        public async get(params: { inviteCode: string }): Promise<ResponseType<typeof api_group_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/${encodeURIComponent(params.inviteCode)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_get_get>
        }

        /**
         * Get chat messages for a group
         */
        public async getChatMessages(params: RequestType<typeof api_group_chat_getChatMessages>): Promise<ResponseType<typeof api_group_chat_getChatMessages>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:     params.limit === undefined ? undefined : String(params.limit),
                offset:    params.offset === undefined ? undefined : String(params.offset),
                userEmail: params.userEmail,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/chat/${encodeURIComponent(params.inviteCode)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_chat_getChatMessages>
        }

        /**
         * Get group check-in information
         */
        public async getGroupCheckIn(params: { inviteCode: string }): Promise<ResponseType<typeof api_group_manage_getGroupCheckIn>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/checkin/${encodeURIComponent(params.inviteCode)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_manage_getGroupCheckIn>
        }

        /**
         * Get all group bookings for a user
         */
        public async getUserGroupBookings(params: RequestType<typeof api_group_get_getUserGroupBookings>): Promise<ResponseType<typeof api_group_get_getUserGroupBookings>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                email: params.email,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/group-bookings`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_get_getUserGroupBookings>
        }

        /**
         * Join a group booking by purchasing tickets
         */
        public async joinGroupBooking(params: RequestType<typeof api_group_book_joinGroupBooking>): Promise<ResponseType<typeof api_group_book_joinGroupBooking>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/join`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_book_joinGroupBooking>
        }

        /**
         * Lock group booking (no more changes allowed)
         */
        public async lockGroupBooking(params: RequestType<typeof api_group_manage_lockGroupBooking>): Promise<ResponseType<typeof api_group_manage_lockGroupBooking>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/lock`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_manage_lockGroupBooking>
        }

        /**
         * Respond to a group booking invitation
         */
        public async respondToInvitation(params: RequestType<typeof api_group_invite_respondToInvitation>): Promise<ResponseType<typeof api_group_invite_respondToInvitation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/respond`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_invite_respondToInvitation>
        }

        /**
         * Send invitations to join a group booking
         */
        public async sendInvitations(params: RequestType<typeof api_group_invite_sendInvitations>): Promise<ResponseType<typeof api_group_invite_sendInvitations>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/invite`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_invite_sendInvitations>
        }

        /**
         * Send a message to the group chat
         */
        public async sendMessage(params: RequestType<typeof api_group_chat_sendMessage>): Promise<ResponseType<typeof api_group_chat_sendMessage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/chat`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_chat_sendMessage>
        }

        /**
         * Send reminders to people who haven't booked yet
         */
        public async sendReminders(params: RequestType<typeof api_group_invite_sendReminders>): Promise<ResponseType<typeof api_group_invite_sendReminders>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/remind`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_invite_sendReminders>
        }

        /**
         * Update group size (only allowed until 48 hours before event)
         */
        public async updateGroupSize(params: RequestType<typeof api_group_book_updateGroupSize>): Promise<ResponseType<typeof api_group_book_updateGroupSize>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/group-bookings/size`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_group_book_updateGroupSize>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { subscribeToEventUpdates as api_realtime_subscribe_subscribeToEventUpdates } from "~backend/realtime/subscribe";

export namespace realtime {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.subscribeToEventUpdates = this.subscribeToEventUpdates.bind(this)
        }

        /**
         * WebSocket support for live dashboard updates
         */
        public async subscribeToEventUpdates(params: { eventId: number }): Promise<StreamIn<StreamResponse<typeof api_realtime_subscribe_subscribeToEventUpdates>>> {
            return await this.baseClient.createStreamIn(`/events/${encodeURIComponent(params.eventId)}/subscribe`)
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getRecommendations as api_recommendation_engine_getRecommendations,
    getSimilarEvents as api_recommendation_engine_getSimilarEvents
} from "~backend/recommendation/engine";

export namespace recommendation {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getRecommendations = this.getRecommendations.bind(this)
            this.getSimilarEvents = this.getSimilarEvents.bind(this)
        }

        /**
         * Get personalized event recommendations
         */
        public async getRecommendations(params: RequestType<typeof api_recommendation_engine_getRecommendations>): Promise<ResponseType<typeof api_recommendation_engine_getRecommendations>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                email:         params.email,
                includeBooked: params.includeBooked === undefined ? undefined : String(params.includeBooked),
                limit:         params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recommendations`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_recommendation_engine_getRecommendations>
        }

        /**
         * Get similar events based on a specific event
         */
        public async getSimilarEvents(params: RequestType<typeof api_recommendation_engine_getSimilarEvents>): Promise<ResponseType<typeof api_recommendation_engine_getSimilarEvents>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                email: params.email,
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recommendations/similar/${encodeURIComponent(params.eventId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_recommendation_engine_getSimilarEvents>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createLead as api_sponsor_lead_capture_createLead } from "~backend/sponsor/lead_capture";
import {
    getEventOpportunities as api_sponsor_packages_getEventOpportunities,
    getPackages as api_sponsor_packages_getPackages
} from "~backend/sponsor/packages";
import {
    respondToProposal as api_sponsor_proposals_respondToProposal,
    trackProposalView as api_sponsor_proposals_trackProposalView
} from "~backend/sponsor/proposals";

export namespace sponsor {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createLead = this.createLead.bind(this)
            this.getEventOpportunities = this.getEventOpportunities.bind(this)
            this.getPackages = this.getPackages.bind(this)
            this.respondToProposal = this.respondToProposal.bind(this)
            this.trackProposalView = this.trackProposalView.bind(this)
        }

        /**
         * Create a new sponsor lead with automatic scoring and package recommendations
         */
        public async createLead(params: RequestType<typeof api_sponsor_lead_capture_createLead>): Promise<ResponseType<typeof api_sponsor_lead_capture_createLead>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sponsor/leads`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sponsor_lead_capture_createLead>
        }

        /**
         * Get sponsorship opportunities for an event
         */
        public async getEventOpportunities(params: { eventId: number }): Promise<ResponseType<typeof api_sponsor_packages_getEventOpportunities>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sponsor/opportunities/${encodeURIComponent(params.eventId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sponsor_packages_getEventOpportunities>
        }

        /**
         * Get all sponsorship packages
         */
        public async getPackages(): Promise<ResponseType<typeof api_sponsor_packages_getPackages>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sponsor/packages`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sponsor_packages_getPackages>
        }

        /**
         * Respond to proposal
         */
        public async respondToProposal(params: RequestType<typeof api_sponsor_proposals_respondToProposal>): Promise<ResponseType<typeof api_sponsor_proposals_respondToProposal>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sponsor/proposals/respond`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sponsor_proposals_respondToProposal>
        }

        /**
         * Track when proposal is viewed
         */
        public async trackProposalView(params: RequestType<typeof api_sponsor_proposals_trackProposalView>): Promise<ResponseType<typeof api_sponsor_proposals_trackProposalView>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sponsor/proposals/track-view`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sponsor_proposals_trackProposalView>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getBookingHistory as api_user_booking_history_getBookingHistory } from "~backend/user/booking_history";

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getBookingHistory = this.getBookingHistory.bind(this)
        }

        /**
         * Get user booking history
         */
        public async getBookingHistory(params: RequestType<typeof api_user_booking_history_getBookingHistory>): Promise<ResponseType<typeof api_user_booking_history_getBookingHistory>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                email:     params.email,
                endDate:   params.endDate,
                limit:     params.limit === undefined ? undefined : String(params.limit),
                offset:    params.offset === undefined ? undefined : String(params.offset),
                startDate: params.startDate,
                status:    params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/booking-history`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_booking_history_getBookingHistory>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getAnalytics as api_venue_analytics_getAnalytics } from "~backend/venue/analytics";
import { getComparison as api_venue_comparison_getComparison } from "~backend/venue/comparison";
import { match as api_venue_match_match } from "~backend/venue/match";
import { getOptimization as api_venue_optimization_getOptimization } from "~backend/venue/optimization";

export namespace venue {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getAnalytics = this.getAnalytics.bind(this)
            this.getComparison = this.getComparison.bind(this)
            this.getOptimization = this.getOptimization.bind(this)
            this.match = this.match.bind(this)
        }

        /**
         * Get comprehensive venue analytics
         */
        public async getAnalytics(params: RequestType<typeof api_venue_analytics_getAnalytics>): Promise<ResponseType<typeof api_venue_analytics_getAnalytics>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                endDate:   params.endDate,
                startDate: params.startDate,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/venues/${encodeURIComponent(params.venue)}/analytics`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_venue_analytics_getAnalytics>
        }

        /**
         * Compare performance across all venues
         */
        public async getComparison(params: RequestType<typeof api_venue_comparison_getComparison>): Promise<ResponseType<typeof api_venue_comparison_getComparison>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                endDate:   params.endDate,
                startDate: params.startDate,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/venues/comparison`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_venue_comparison_getComparison>
        }

        /**
         * Get optimization recommendations for a venue
         */
        public async getOptimization(params: { venue: string }): Promise<ResponseType<typeof api_venue_optimization_getOptimization>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/venues/${encodeURIComponent(params.venue)}/optimization`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_venue_optimization_getOptimization>
        }

        /**
         * Match venues based on event requirements
         */
        public async match(params: RequestType<typeof api_venue_match_match>): Promise<ResponseType<typeof api_venue_match_match>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/venues/match`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_venue_match_match>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.49.1)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
